### ISSUE TITLE
Updates todo

### ISSUE THREAD

**Issue by vankasteelj** [vankasteelj/frak#95]
- [x] Update NWJS
  - [x] update nwjs version
  - [x] fix runtime.lastError (the issue comes from using requestAttention)
  - [ ] figure out win.requestAttention() (doesn't work with 0.49.2)
  - [x] figure out win.setProgressBar() (works with 0.49.2 and above)

- [x] Update MPV
  - [x] update MPV version
  - [x] update node-mpv module

- [ ] Update Cheerio
